use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "2a122eyxG4T1vkoqErfpoWt7eSHKW1aZJwD5VbWbysVS7Bo3YfXGeV2"
  limiter: false
  public_instance: false

search:
  safe_search: 1
  autocomplete: "google"
  default_lang: "en"
  formats:
    - html
    - json

ui:
  static_use_hash: true
  default_locale: "en"
  query_in_title: false

engines:
  - name: google
    engine: google
    categories: general
    disabled: false

  - name: bing
    engine: bing
    categories: general
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    categories: general
    disabled: false

# Disable bot detection for API access
botdetection:
  ip_limit:
    filter_link_local: false
    link_token: false
  ip_lists:
    pass_ip: []
    block_ip: []